config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'welcome/about'
  get 'welcome/contact'
  get 'welcome/features'
  get 'welcome/faq'
  get 'welcome/pricing'

  resources :invoices

  root to: 'welcome#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invoice.rb
class Invoice < ApplicationRecord
end

app/models/invoice_search.rb
class InvoiceSearch
	attr_reader :date_from, :date_to

	def initialize(params)
		params ||= {}
		@date_from = parsed_date(params[:date_from], 7.days.ago.to_date.to_s)
		@date_to = parsed_date(params[:date_to], Date.today.to_s)
	end

	def scope
		Invoice.where("date BETWEEN ? AND ?", @date_from, @date_to)
	end

	private

	def parsed_date(date_string, default)
		Date.parse(date_string)
	rescue ArgumentError, TypeError
		default
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @search = InvoiceSearch.new(params[:search])
    @invoices = @search.scope
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:date, :company, :tax, :salesperson)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def features
  end

  def faq
  end

  def pricing
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/invoices/_form.html.erb
<%= form_with(model: invoice, local: true) do |form| %>
  <% if invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% invoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :company %>
    <%= form.text_field :company %>
  </div>

  <div class="field">
    <%= form.label :tax %>
    <%= form.text_field :tax %>
  </div>

  <div class="field">
    <%= form.label :salesperson %>
    <%= form.text_field :salesperson %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<h1>Editing Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <h1>Listing Invoices</h1>
  <div class="pull-right range-query">
    <%= form_tag invoices_path, method: :get do  %>
      <%= text_field_tag "search[date_from]", @search.date_from %>
      <%= text_field_tag "search[date_to]", @search.date_to %>
      <%= submit_tag "Search", class: 'btn search-button' %>
    <% end %>
  </div>
</div>

<div class="media">
  <div class="media-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Date</th>
          <th>Company</th>
          <th>Tax</th>
          <th>Salesperson</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @invoices.each do |invoice| %>
          <tr>
            <td><%= invoice.date.strftime("%Y/%m/%d") %></td>
            <td><%= invoice.company %></td>
            <td><%= invoice.tax %></td>
            <td><%= invoice.salesperson %></td>
            <td><%= link_to 'View', invoice, class: 'btn btn-mini' %></td>
            <td><%= link_to 'Edit', edit_invoice_path(invoice), class: 'btn btn-mini btn-success' %></td>
            <td><%= link_to 'Delete', invoice, method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>

<%= link_to 'New Invoice', new_invoice_path %>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @invoice.date %>
</p>

<p>
  <strong>Company:</strong>
  <%= @invoice.company %>
</p>

<p>
  <strong>Tax:</strong>
  <%= @invoice.tax %>
</p>

<p>
  <strong>Salesperson:</strong>
  <%= @invoice.salesperson %>
</p>

<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Enterpriseape</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About Us", welcome_about_path %></li>
        <li><%= link_to "Contact", welcome_contact_path %></li>
        <li><%= link_to "Features", welcome_features_path %></li>
        <li><%= link_to "Pricing", welcome_pricing_path %></li>
        <li><%= link_to "FAQs", welcome_faq_path %></li>
        <li><%= link_to "Invoices", invoices_path %></li>
        <li><%= link_to "Login", root_path %></li>
      </ul>

      <%= yield %>

    </div>
  </body>
</html>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/contact.html.erb
<h1>Welcome#contact</h1>
<p>Find me in app/views/welcome/contact.html.erb</p>

app/views/welcome/faq.html.erb
<h1>Welcome#faq</h1>
<p>Find me in app/views/welcome/faq.html.erb</p>

app/views/welcome/features.html.erb
<h1>Welcome#features</h1>
<p>Find me in app/views/welcome/features.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/welcome/pricing.html.erb
<h1>Welcome#pricing</h1>
<p>Find me in app/views/welcome/pricing.html.erb</p>